name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  branch:
    uses: ./.github/workflows/branch.yml

  config:
    uses: ./.github/workflows/config.yml
    needs: [ branch ]
    with:
      phase: ${{ needs.branch.outputs.branch }}
